# 定义多语言字典
LANGUAGES = {
    "en": {
        "input": "Input Part / Assembly / Project Number :",
        "search_pdf": "Search PDF Drawing",
        "lucky": "I'm Feeling Lucky !",
        "3d": "Search 3D Drawing",
        "vault": "Search in Vault Cache",
        "reset": "Reset",
        "quick": "Quick Access",
        "default_parts_dir": "Default PARTS directory:",
        "parts_dir": "PARTS Directory",
        "change": "Change",
        "default": "Default",
        "tip_top": "Pin to top",
        "tip_mini": "Switch to mini window",
        "tip_search_pdf": "Search for PDF files matching the entered keywords",
        "tip_lucky": "Open the latest revision of the PDF drawing",
        "tip_3d": "Search for 3D files (.iam/.ipt) matching the entered keywords",
        "tip_vault": "Search 3D drawings (.iam/.ipt) from local Vault cache\rSupport searching by project name",
        "tip_reset": "Reset the window to default, stop the current search\rand clear search cache",
        "tip_quick": "Shortcuts to frequently used folders and files",
        "tip_change": "Select a new PARTS directory",
        "tip_default": "Reset the PARTS directory to default",
        "tip_about": "About",
        "tip_refresh": "Click repeatedly to refresh the cached directories",
        "no_cache": "No cache",
        "cache_completed": "Cache completed:",
        "cache_in_progress": "Caching in progress",
        "language": "Passer en français",
        "preview": "Preview",
        "show_preview": "Show previews",
        "warning": "Warning",
        "no_missing_list": "No Missing List file found!",
        "no_labels_file": "No Equipment Labels Details file found!",
        "error": "Error",
        "failed_to_open_shortcut": "Failed to open shortcut",
        "shortcut_not_exist": "Shortcut path does not exist",
        "failed_to_open_file": "Failed to open file",
        "file_not_found": "File not found!",
        "error_cache": "An error occurred in cache thread",
        "timeout_click": "Timeout click!",
        "continue_click_1": "Continue clicking",
        "continue_click_2": "times (in 5 sec) to refresh the cache",
        "cache_refreshing": "Cache is refreshing in the background...",
        "enter_number": "Please enter any number or project name!",
        "invalid_characters": "Invalid characters in search query!",
        "path_not_exist": "Path does not exist!",
        "searching": "Searching... Please wait.",
        "no_matching_pdf": "No matching drawing PDF found!",
        "no_matching_3d": "No matching 3D drawing found! Try using Vault Cache.",
        "error_search": "An error occurred in search thread",
        "vault_cache_not_found": "Vault cache not found! Please use Vault instead.",
        "no_matching_3d_cache": "No matching 3D drawings are cached. Check in Vault!",
        "cancelled": "Cancelled!",
        "not_latest": "Tip: Searched from cache, may not be the latest update!",
        "select_project": "Select Project",
        "multiple_projects": "Multiple projects were found, please select:",
        "cancel": "Cancel",
        "file": "file",
        "found_open": "found. Double-click to open.",
        "remove_search_results": "Remove search results list",
        "file_name": "File Name",
        "created_time": "Created Time",
        "open": "Open",
        "open_file_location": "Open File Location",
        "unable_pdf": "Unable to read PDF",
        "unable_preview": "Unable to generate preview",
        "about": "About",
        "about_text_1": "This application is a lightweight utility\ndesigned for quick access to drawings\non BellatRx computers.",
        "about_text_2": "If you have any questions or suggestions,\nplease feel free to contact me.",
        "about_text_3": "Developed by: Wei Tang",
        "email": "Email me",
        "failed_email": "Failed to open email client",
        "cut": "Cut",
        "copy": "Copy",
        "paste": "Paste",
        "search": "Search",
        "parts_folder": "PARTS folder",
    },
    "fr": {
        "input": "N° Pièce / Assemblage / Projet :",
        "search_pdf": "Rechercher PDF",
        "lucky": "J'ai de la chance !",
        "3d": "Rechercher le dessin 3D",
        "vault": "Rechercher dans Vault",
        "reset": "Réinitialiser",
        "quick": "Accès rapide",
        "default_parts_dir": "Répertoire PARTS par défaut:",
        "parts_dir": "Répertoire PARTS",
        "change": "Changer",
        "default": "Par défaut",
        "tip_top": "Épingler en haut",
        "tip_mini": "Passer en mode mini-fenêtre",
        "tip_search_pdf": "Rechercher des fichiers PDF correspondant aux mots-clés saisis",
        "tip_lucky": "Ouvrir la dernière révision du dessin PDF",
        "tip_3d": "Rechercher des fichiers 3D (.iam/.ipt) correspondant aux mots-clés saisis",
        "tip_vault": "Rechercher des dessins 3D (.iam/.ipt) dans le cache local Vault\rPrise en charge de la recherche par nom de projet",
        "tip_reset": "Réinitialiser la fenêtre par défaut, arrêter la recherche en cours\ret effacer le cache de recherche",
        "tip_quick": "Raccourcis vers les dossiers et fichiers fréquemment utilisés",
        "tip_change": "Sélectionner un nouveau répertoire PARTS",
        "tip_default": "Réinitialiser le répertoire PARTS par défaut",
        "tip_about": "À propos",
        "tip_refresh": "Cliquer plusieurs fois pour actualiser les répertoires mis en cache",
        "no_cache": "Pas de cache",
        "cache_completed": "Cache terminé:",
        "cache_in_progress": "Mise en cache en cours:",
        "language": "Switch to English",
        "preview": "Aperçu",
        "show_preview": "Afficher les aperçus",
        "warning": "Avertissement",
        "no_missing_list": "Aucun fichier de liste manquante trouvé!",
        "no_labels_file": "Aucun fichier de détails des étiquettes d'équipement trouvé!",
        "error": "Erreur",
        "failed_to_open_shortcut": "Échec de l'ouverture du raccourci",
        "shortcut_not_exist": "Le chemin du raccourci n'existe pas",
        "failed_to_open_file": "Échec de l'ouverture du fichier",
        "file_not_found": "Fichier introuvable!",
        "error_cache": "Une erreur s'est produite dans le thread de cache",
        "timeout_click": "Délai d'attente pour le clic!",
        "continue_click_1": "Continuez",
        "continue_click_2": "clics (en 5 sec) pour actualiser le cache",
        "cache_refreshing": "Le cache se rafraîchit en arrière-plan...",
        "enter_number": "Veuillez entrer un numéro ou un nom de projet!",
        "invalid_characters": "Caractères invalides dans la requête de recherche!",
        "path_not_exist": "Le chemin n'existe pas!",
        "searching": "Recherche en cours... Veuillez patienter.",
        "no_matching_pdf": "Aucun dessin PDF correspondant trouvé!",
        "no_matching_3d": "Aucun dessin 3D trouvé! Essayez d'utiliser le cache Vault.",
        "error_search": "Une erreur s'est produite dans le thread de recherche",
        "vault_cache_not_found": "Cache Vault introuvable! Veuillez utiliser Vault à la place.",
        "no_matching_3d_cache": "Aucun dessin 3D en cache. Vérifiez dans Vault!",
        "cancelled": "Annulé!",
        "not_latest": "Astuce: Recherche depuis le cache, pas forcément à jour!",
        "select_project": "Choisir un projet",
        "multiple_projects": "Plusieurs projets trouvés, veuillez sélectionner:",
        "cancel": "Annuler",
        "file": "fichier",
        "found_open": "trouvé. Double-cliquez pour ouvrir.",
        "remove_search_results": "Supprimer la liste des résultats de recherche",
        "file_name": "Nom de fichier",
        "created_time": "Date de création",
        "open": "Ouvrir",
        "open_file_location": "Ouvrir l'emplacement du fichier",
        "unable_pdf": "Impossible de lire le PDF",
        "unable_preview": "Impossible de générer un aperçu",
        "about": "À propos",
        "about_text_1": "Cette application est un utilitaire léger\nconçu pour un accès rapide aux dessins\nsur les ordinateurs BellatRx.",
        "about_text_2": "Si vous avez des questions ou des\nsuggestions, n'hésitez pas à me contacter.",
        "about_text_3": "Développé par: Wei Tang",
        "email": "Courriel",
        "failed_email": "Échec de l'ouverture du client de messagerie",
        "cut": "Couper",
        "copy": "Copier",
        "paste": "Coller",
        "search": "Rechercher",
        "parts_folder": "Dossier PARTS",
    }
}