# 定义多语言字典
LANGUAGES = {
    "en": {
        "input": "Input Part / Assembly / Project Number :",
        "search_pdf": "Search PDF Drawing",
        "lucky": "I'm Feeling Lucky !",
        "3d": "Search 3D Drawing",
        "vault": "Search in Vault Cache",
        "partname": "Search Part Name",
        "reset": "Reset",
        "quick": "Quick Access",
        "default_parts_dir": "Default PARTS directory:",
        "parts_dir": "PARTS Directory",
        "change": "Change",
        "default": "Default",
        "tip_top": "Pin to top\rShortcut keys: Alt+T",
        "tip_mini": "Switch to mini window\rShortcut keys: Alt+M",
        "tip_search_pdf": "Search for PDF files matching the entered keywords.\rShortcut keys: Alt+P",
        "tip_lucky": "Open the latest revision of the PDF drawing.\rShortcut keys: Alt+L",
        "tip_3d": "Search for 3D files (.iam/.ipt) matching the entered keywords.\rShortcut keys: Alt+D",
        "tip_vault": "Search 3D drawings (.iam/.ipt) from local Vault cache.\rSupport searching by project name.\rShortcut keys: Alt+V",
        "tip_partname": "Search for Part Name matching the entered keywords.\rBut it doesn't include all parts. Find more results in Vault.\rShortcut keys: Alt+N",
        "tip_reset": "Reset the window to default, stop the current search\rand clear search cache.\rShortcut keys: Alt+R",
        "tip_quick": "Shortcuts to frequently used folders and files.\rShortcut keys: Alt+Q",
        "tip_change": "Select a new PARTS directory",
        "tip_default": "Reset the PARTS directory to default",
        "tip_about": "About\rShortcut keys: Alt+A",
        "tip_refresh": "Click repeatedly to refresh the cached directories",
        "no_cache": "No cache",
        "cache_completed": "Cache completed:",
        "cache_in_progress": "Caching in progress:",
        "language": "Passer en français\rRaccourcis clavier: Alt+S",
        "preview": "Preview",
        "show_preview": "Show previews",
        "warning": "Warning",
        "no_missing_list": "No Missing List file found!",
        "no_labels_file": "No Equipment Labels Details file found!",
        "error": "Error",
        "failed_to_open_shortcut": "Failed to open shortcut",
        "shortcut_not_exist": "Shortcut path does not exist",
        "failed_to_open_file": "Failed to open file",
        "file_not_found": "File not found",
        "error_cache": "An error occurred in cache thread",
        "timeout_click": "Timeout click!",
        "continue_click_1": "Continue clicking",
        "continue_click_2": "times (in 5 sec) to refresh the cache",
        "cache_refreshing": "Cache is refreshing in the background...",
        "enter_number": "Please enter any number or project name!",
        "invalid_characters": "Invalid characters in search query!",
        "path_not_exist": "Path does not exist!",
        "searching": "Searching... Please wait.",
        "no_matching_pdf": "No matching drawing PDF found!",
        "no_matching_3d": "No matching 3D drawing found! Try using Vault Cache.",
        "error_search": "An error occurred in search thread",
        "vault_cache_not_found": "Vault cache not found! Please use Vault instead.",
        "no_matching_3d_cache": "No matching 3D drawings are cached. Check in Vault!",
        "cancelled": "Cancelled!",
        "not_latest": "Tip: Searched from cache, may not be the latest update!",
        "select_project": "Select Project",
        "multiple_projects": "Multiple projects were found, please select:",
        "cancel": "Cancel",
        "item": "item",
        "found_open": "found. Double/Right-click to open.",
        "remove_search_results": "Remove search results list",
        "file_name": "File Name",
        "created_time": "Created Time",
        "open": "Open",
        "no_drawing_open": "No drawings available to open",
        "open_file_location": "Open File Location",
        "open_pdf": "Open PDF Drawing",
        "pdf_not_found": "PDF file not found",
        "open_ipt": "Open IPT Drawing",
        "ipt_not_found": "IPT file not found",
        "open_iam": "Open IAM Drawing",
        "iam_not_found": "IAM file not found",
        "unable_pdf": "Unable to read PDF",
        "unable_preview": "Unable to generate preview",
        "about": "About",
        "about_text_1": "This application is a lightweight utility\rdesigned for quick access to drawings\ron BellatRx computers.",
        "about_text_2": "If you have any questions or suggestions,\rplease feel free to contact me.",
        "about_text_3": "Developed by: Wei Tang",
        "email": "Email me",
        "failed_email": "Failed to open email client",
        "cut": "Cut",
        "copy": "Copy",
        "paste": "Paste",
        "search": "Search",
        "update_download": "Update available, click to download",
        "already_latest": "You are already using the latest version.",
        "enter_search": "Press ⏎ to search PDF",
        "esc_return": "Esc to return here",
        "first_partname_1": "First time searching for Part Name?",
        "first_partname_2": "No part name data found. It will be generated\rin the background (about 30 mins).",
        "first_partname_3": "Keep the main window open. You will get a\rpopup when it's done.",
        "partname_generated": "Finished generating part name data!",
        "partname_generating": "Part name data is being generated. Please wait.",
        "no_matching_name": "No matching part name found. (Not all parts included)",
        "part_no": "Part No.",
        "name": "Name",
        "drawing": "Drawing",
        "file_path": "File Path: ",
        "delete_data": "You can delete it manually to regenerate the latest data.",
        "update_check_failed": "Update check failed. Please try again later.",
        "cpoied_part_number": "Tip: Click the button to search the copied part number.",
    },
    "fr": {
        "input": "N° Pièce / Assemblage / Projet :",
        "search_pdf": "Rechercher PDF",
        "lucky": "J'ai de la chance !",
        "3d": "Rechercher 3D",
        "vault": "Rechercher dans Vault",
        "partname": "Rechercher Nom",
        "reset": "Réinitialiser",
        "quick": "Accès rapide",
        "default_parts_dir": "Répertoire PARTS par défaut:",
        "parts_dir": "Répertoire PARTS",
        "change": "Changer",
        "default": "Par défaut",
        "tip_top": "Épingler en haut\rRaccourcis clavier: Alt+T",
        "tip_mini": "Passer en mode mini-fenêtre\rRaccourcis clavier: Alt+M",
        "tip_search_pdf": "Rechercher des fichiers PDF correspondant aux mots-clés saisis.\rRaccourcis clavier: Alt+P",
        "tip_lucky": "Ouvrir la dernière révision du dessin PDF.\rRaccourcis clavier: Alt+L",
        "tip_3d": "Rechercher des fichiers 3D (.iam/.ipt) correspondant aux mots-clés saisis.\rRaccourcis clavier: Alt+D",
        "tip_vault": "Rechercher des dessins 3D (.iam/.ipt) dans le cache local Vault.\rPrise en charge de la recherche par nom de projet.\rRaccourcis clavier: Alt+V",
        "tip_partname": "Rechercher le nom de la pièce correspondant aux mots-clés saisis.\rToutes les pièces ne sont pas incluses. Voir plus dans Vault.\rRaccourcis clavier: Alt+N",
        "tip_reset": "Réinitialiser la fenêtre par défaut, arrêter la recherche en cours\ret effacer le cache de recherche.\rRaccourcis clavier: Alt+R",
        "tip_quick": "Raccourcis vers les dossiers et fichiers fréquemment utilisés.\rRaccourcis clavier: Alt+Q",
        "tip_change": "Sélectionner un nouveau répertoire PARTS",
        "tip_default": "Réinitialiser le répertoire PARTS par défaut",
        "tip_about": "À propos\rRaccourcis clavier: Alt+A",
        "tip_refresh": "Cliquer plusieurs fois pour actualiser les répertoires mis en cache",
        "no_cache": "Pas de cache",
        "cache_completed": "Cache terminé:",
        "cache_in_progress": "Mise en cache en cours:",
        "language": "Switch to English\rShortcut keys: Alt+S",
        "preview": "Aperçu",
        "show_preview": "Afficher les aperçus",
        "warning": "Avertissement",
        "no_missing_list": "Aucun fichier de liste manquante trouvé!",
        "no_labels_file": "Aucun fichier de détails des étiquettes d'équipement trouvé!",
        "error": "Erreur",
        "failed_to_open_shortcut": "Échec de l'ouverture du raccourci",
        "shortcut_not_exist": "Le chemin du raccourci n'existe pas",
        "failed_to_open_file": "Échec de l'ouverture du fichier",
        "file_not_found": "Fichier introuvable",
        "error_cache": "Une erreur s'est produite dans le thread de cache",
        "timeout_click": "Délai d'attente pour le clic!",
        "continue_click_1": "Continuez",
        "continue_click_2": "clics (en 5 sec) pour actualiser le cache",
        "cache_refreshing": "Le cache se rafraîchit en arrière-plan...",
        "enter_number": "Veuillez entrer un numéro ou un nom de projet!",
        "invalid_characters": "Caractères invalides dans la requête de recherche!",
        "path_not_exist": "Le chemin n'existe pas!",
        "searching": "Recherche en cours... Veuillez patienter.",
        "no_matching_pdf": "Aucun dessin PDF correspondant trouvé!",
        "no_matching_3d": "Aucun dessin 3D trouvé! Essayez d'utiliser le cache Vault.",
        "error_search": "Une erreur s'est produite dans le thread de recherche",
        "vault_cache_not_found": "Cache Vault introuvable! Veuillez utiliser Vault à la place.",
        "no_matching_3d_cache": "Aucun dessin 3D en cache. Vérifiez dans Vault!",
        "cancelled": "Annulé!",
        "not_latest": "Astuce: Recherche depuis le cache, pas forcément à jour!",
        "select_project": "Choisir un projet",
        "multiple_projects": "Plusieurs projets trouvés, veuillez sélectionner:",
        "cancel": "Annuler",
        "item": "article",
        "found_open": "trouvé. Double/clic droit pour ouvrir.",
        "remove_search_results": "Supprimer la liste des résultats de recherche",
        "file_name": "Nom de fichier",
        "created_time": "Date de création",
        "open": "Ouvrir",
        "no_drawing_open": "Aucun dessin disponible à ouvrir",
        "open_file_location": "Ouvrir l'emplacement du fichier",
        "open_pdf": "Ouvrir le dessin PDF",
        "pdf_not_found": "Fichier PDF introuvable",
        "open_ipt": "Ouvrir le dessin IPT",
        "ipt_not_found": "Fichier IPT introuvable",
        "open_iam": "Ouvrir le dessin IAM",
        "iam_not_found": "Fichier IAM introuvable",
        "unable_pdf": "Impossible de lire le PDF",
        "unable_preview": "Impossible de générer un aperçu",
        "about": "À propos",
        "about_text_1": "Cette application est un utilitaire léger\rconçu pour un accès rapide aux dessins\rsur les ordinateurs BellatRx.",
        "about_text_2": "Si vous avez des questions ou des\rsuggestions, n'hésitez pas à me contacter.",
        "about_text_3": "Développé par: Wei Tang",
        "email": "Courriel",
        "failed_email": "Échec de l'ouverture du client de messagerie",
        "cut": "Couper",
        "copy": "Copier",
        "paste": "Coller",
        "search": "Rechercher",
        "update_download": "Télécharger la nouvelle version",
        "already_latest": "Vous utilisez déjà la dernière version.",
        "enter_search": "⏎ pour rechercher PDF",
        "esc_return": "Échap pour revenir ici",
        "first_partname_1": "Première recherche de nom de pièce?",
        "first_partname_2": "Aucune donnée de nom de pièce trouvée. Elle\rsera générée en arrière-plan (environ 30 minutes).",
        "first_partname_3": "Gardez la fenêtre principale ouverte. Vous\rrecevrez une notification lorsque ce sera terminé.",
        "partname_generated": "Les données de nom de pièce ont été générées.",
        "partname_generating": "Génération des données de nom de pièce en cours.",
        "no_matching_name": "Aucun nom de pièce trouvé. (Pièces manquantes)",
        "part_no": "N° Pièce",
        "name": "Nom",
        "drawing": "Dessin",
        "file_path": "Chemin du fichier: ",
        "delete_data": "Vous pouvez le supprimer manuellement pour régénérer les données les plus récentes.",
        "update_check_failed": "Échec de la mise à jour. Réessayez plus tard.",
        "cpoied_part_number": "Astuce: Cliquez pour rechercher le numéro copié.",
    }
}